// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GeminiDeepResearchSyncData, GeminiDeepResearchSyncResponse, GeminiStartDeepResearchData, GeminiStartDeepResearchResponse, GeminiPollDeepResearchData, GeminiPollDeepResearchResponse, GeminiCancelDeepResearchData, GeminiCancelDeepResearchResponse, ItemsReadItemsData, ItemsReadItemsResponse, ItemsCreateItemData, ItemsCreateItemResponse, ItemsReadItemData, ItemsReadItemResponse, ItemsUpdateItemData, ItemsUpdateItemResponse, ItemsDeleteItemData, ItemsDeleteItemResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, PerplexityDeepResearchData, PerplexityDeepResearchResponse2, PrivateCreateUserData, PrivateCreateUserResponse, TavilySearchData, TavilySearchResponse, TavilyExtractData, TavilyExtractResponse, TavilyCrawlData, TavilyCrawlResponse, TavilyMapUrlsData, TavilyMapUrlsResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class GeminiService {
    /**
     * Deep Research Sync
     * Execute a deep research query and wait for completion.
     *
     * Starts a deep research job and blocks until the job reaches a terminal
     * state (completed, failed, or cancelled). This is a convenience endpoint
     * for clients that prefer a synchronous workflow.
     *
     * Note: This endpoint may take 20-60 minutes to complete for complex queries.
     * Consider using the async workflow (POST + polling) for better control.
     *
     * Args:
     * _current_user: Authenticated user (required for authorization).
     * gemini: Injected GeminiService instance.
     * request: Deep research request with query and optional parameters.
     *
     * Returns:
     * GeminiDeepResearchResultResponse with final status and results.
     *
     * Raises:
     * GeminiAPIError: If the job fails or polling exceeds max attempts.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns GeminiDeepResearchResultResponse Successful Response
     * @throws ApiError
     */
    public static deepResearchSync(data: GeminiDeepResearchSyncData): CancelablePromise<GeminiDeepResearchSyncResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/gemini/deep-research/sync',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Start Deep Research
     * Start a new deep research job.
     *
     * Submits a research query to the Gemini API and returns immediately with
     * an interaction ID. Use the poll endpoint to check job status and retrieve
     * results when complete.
     *
     * Args:
     * _current_user: Authenticated user (required for authorization).
     * gemini: Injected GeminiService instance.
     * request: Deep research request with query and optional parameters.
     *
     * Returns:
     * GeminiDeepResearchJobResponse with interaction_id and initial status.
     *
     * Raises:
     * GeminiAPIError: If the API request fails for any reason.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns GeminiDeepResearchJobResponse Successful Response
     * @throws ApiError
     */
    public static startDeepResearch(data: GeminiStartDeepResearchData): CancelablePromise<GeminiStartDeepResearchResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/gemini/deep-research',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Poll Deep Research
     * Poll for deep research job status and results.
     *
     * Retrieves the current status and any available outputs from a running
     * research job. The last_event_id parameter enables reconnection after
     * network interruption, allowing clients to resume from where they left off.
     *
     * Args:
     * _current_user: Authenticated user (required for authorization).
     * gemini: Injected GeminiService instance.
     * interaction_id: The interaction ID from job creation.
     * last_event_id: Optional ID of last received event for reconnection.
     *
     * Returns:
     * GeminiDeepResearchResultResponse with current status and outputs.
     *
     * Raises:
     * GeminiAPIError: If the interaction is not found or polling fails.
     * @param data The data for the request.
     * @param data.interactionId
     * @param data.lastEventId
     * @returns GeminiDeepResearchResultResponse Successful Response
     * @throws ApiError
     */
    public static pollDeepResearch(data: GeminiPollDeepResearchData): CancelablePromise<GeminiPollDeepResearchResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/gemini/deep-research/{interaction_id}',
            path: {
                interaction_id: data.interactionId
            },
            query: {
                last_event_id: data.lastEventId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Cancel Deep Research
     * Cancel a running deep research job.
     *
     * Terminates a running research job. Returns successfully if the job was
     * cancelled or was already in a terminal state.
     *
     * Args:
     * _current_user: Authenticated user (required for authorization).
     * gemini: Injected GeminiService instance.
     * interaction_id: The interaction ID of the job to cancel.
     *
     * Returns:
     * Success message confirming cancellation.
     *
     * Raises:
     * GeminiAPIError: If the cancellation request fails.
     * @param data The data for the request.
     * @param data.interactionId
     * @returns string Successful Response
     * @throws ApiError
     */
    public static cancelDeepResearch(data: GeminiCancelDeepResearchData): CancelablePromise<GeminiCancelDeepResearchResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/gemini/deep-research/{interaction_id}',
            path: {
                interaction_id: data.interactionId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ItemsService {
    /**
     * Read Items
     * Retrieve items with optional content_type filter.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @param data.contentType
     * @returns ItemsPublic Successful Response
     * @throws ApiError
     */
    public static readItems(data: ItemsReadItemsData = {}): CancelablePromise<ItemsReadItemsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/',
            query: {
                skip: data.skip,
                limit: data.limit,
                content_type: data.contentType
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Item
     * Create new item.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static createItem(data: ItemsCreateItemData): CancelablePromise<ItemsCreateItemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/items/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Item
     * Get item by ID.
     * @param data The data for the request.
     * @param data.id
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static readItem(data: ItemsReadItemData): CancelablePromise<ItemsReadItemResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Item
     * Update an item.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static updateItem(data: ItemsUpdateItemData): CancelablePromise<ItemsUpdateItemResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Item
     * Delete an item.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteItem(data: ItemsDeleteItemData): CancelablePromise<ItemsDeleteItemResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PerplexityService {
    /**
     * Deep Research
     * Execute a deep research query using Perplexity Sonar API.
     *
     * Performs a deep research query with the provided parameters, returning
     * a comprehensive response with citations and search results.
     *
     * Args:
     * _current_user: Authenticated user (required for authorization).
     * perplexity: Injected PerplexityService instance.
     * request: Deep research request with query and optional parameters.
     *
     * Returns:
     * PerplexityDeepResearchResponse with model response and citations.
     *
     * Raises:
     * PerplexityAPIError: If the Perplexity API request fails.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns PerplexityDeepResearchResponse Successful Response
     * @throws ApiError
     */
    public static deepResearch(data: PerplexityDeepResearchData): CancelablePromise<PerplexityDeepResearchResponse2> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/perplexity/deep-research',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class TavilyService {
    /**
     * Search
     * Perform a web search using Tavily API.
     *
     * Executes a web search with the provided query and parameters, returning
     * relevant search results and optionally an AI-generated answer.
     *
     * Args:
     * current_user: Authenticated user (required for authorization).
     * tavily: Injected TavilyService instance.
     * request: Search request with query and optional parameters.
     *
     * Returns:
     * SearchResponse with query, results, and optional answer/images.
     *
     * Raises:
     * TavilyAPIError: If the Tavily API request fails.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns SearchResponse Successful Response
     * @throws ApiError
     */
    public static search(data: TavilySearchData): CancelablePromise<TavilySearchResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/tavily/search',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Extract
     * Extract content from one or more URLs.
     *
     * Uses Tavily extraction API to retrieve clean, structured content from
     * web pages. Supports both single URL and batch URL extraction.
     *
     * Args:
     * current_user: Authenticated user (required for authorization).
     * tavily: Injected TavilyService instance.
     * request: Extract request with URL or list of URLs.
     *
     * Returns:
     * ExtractResponse with extraction results for each URL.
     *
     * Raises:
     * TavilyAPIError: If the Tavily API request fails.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ExtractResponse Successful Response
     * @throws ApiError
     */
    public static extract(data: TavilyExtractData): CancelablePromise<TavilyExtractResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/tavily/extract',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Crawl
     * Crawl a website starting from a given URL.
     *
     * Performs recursive crawling of a website, extracting content from
     * discovered pages up to the specified depth and breadth limits.
     *
     * Args:
     * current_user: Authenticated user (required for authorization).
     * tavily: Injected TavilyService instance.
     * request: Crawl request with URL and crawl parameters.
     *
     * Returns:
     * CrawlResponse with base URL, crawled page results, and total count.
     *
     * Raises:
     * TavilyAPIError: If the Tavily API request fails.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns CrawlResponse Successful Response
     * @throws ApiError
     */
    public static crawl(data: TavilyCrawlData): CancelablePromise<TavilyCrawlResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/tavily/crawl',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Map Urls
     * Generate a sitemap of URLs from a website.
     *
     * Discovers and returns URLs from a website without extracting content.
     * Useful for understanding site structure before targeted extraction.
     *
     * Args:
     * current_user: Authenticated user (required for authorization).
     * tavily: Injected TavilyService instance.
     * request: Map request with URL and mapping parameters.
     *
     * Returns:
     * MapResponse with base URL, discovered URLs, and total count.
     *
     * Raises:
     * TavilyAPIError: If the Tavily API request fails.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns MapResponse Successful Response
     * @throws ApiError
     */
    public static mapUrls(data: TavilyMapUrlsData): CancelablePromise<TavilyMapUrlsResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/tavily/map',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}