/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutSearchRouteImport } from './routes/_layout/search'
import { Route as LayoutPerplexityResearchRouteImport } from './routes/_layout/perplexity-research'
import { Route as LayoutMapRouteImport } from './routes/_layout/map'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutGeminiResearchRouteImport } from './routes/_layout/gemini-research'
import { Route as LayoutExtractRouteImport } from './routes/_layout/extract'
import { Route as LayoutCrawlRouteImport } from './routes/_layout/crawl'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSearchRoute = LayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPerplexityResearchRoute =
  LayoutPerplexityResearchRouteImport.update({
    id: '/perplexity-research',
    path: '/perplexity-research',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutMapRoute = LayoutMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGeminiResearchRoute = LayoutGeminiResearchRouteImport.update({
  id: '/gemini-research',
  path: '/gemini-research',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExtractRoute = LayoutExtractRouteImport.update({
  id: '/extract',
  path: '/extract',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCrawlRoute = LayoutCrawlRouteImport.update({
  id: '/crawl',
  path: '/crawl',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/crawl': typeof LayoutCrawlRoute
  '/extract': typeof LayoutExtractRoute
  '/gemini-research': typeof LayoutGeminiResearchRoute
  '/items': typeof LayoutItemsRoute
  '/map': typeof LayoutMapRoute
  '/perplexity-research': typeof LayoutPerplexityResearchRoute
  '/search': typeof LayoutSearchRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/crawl': typeof LayoutCrawlRoute
  '/extract': typeof LayoutExtractRoute
  '/gemini-research': typeof LayoutGeminiResearchRoute
  '/items': typeof LayoutItemsRoute
  '/map': typeof LayoutMapRoute
  '/perplexity-research': typeof LayoutPerplexityResearchRoute
  '/search': typeof LayoutSearchRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/crawl': typeof LayoutCrawlRoute
  '/_layout/extract': typeof LayoutExtractRoute
  '/_layout/gemini-research': typeof LayoutGeminiResearchRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/map': typeof LayoutMapRoute
  '/_layout/perplexity-research': typeof LayoutPerplexityResearchRoute
  '/_layout/search': typeof LayoutSearchRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/crawl'
    | '/extract'
    | '/gemini-research'
    | '/items'
    | '/map'
    | '/perplexity-research'
    | '/search'
    | '/settings'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/crawl'
    | '/extract'
    | '/gemini-research'
    | '/items'
    | '/map'
    | '/perplexity-research'
    | '/search'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/crawl'
    | '/_layout/extract'
    | '/_layout/gemini-research'
    | '/_layout/items'
    | '/_layout/map'
    | '/_layout/perplexity-research'
    | '/_layout/search'
    | '/_layout/settings'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/search': {
      id: '/_layout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LayoutSearchRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/perplexity-research': {
      id: '/_layout/perplexity-research'
      path: '/perplexity-research'
      fullPath: '/perplexity-research'
      preLoaderRoute: typeof LayoutPerplexityResearchRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/map': {
      id: '/_layout/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof LayoutMapRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/gemini-research': {
      id: '/_layout/gemini-research'
      path: '/gemini-research'
      fullPath: '/gemini-research'
      preLoaderRoute: typeof LayoutGeminiResearchRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/extract': {
      id: '/_layout/extract'
      path: '/extract'
      fullPath: '/extract'
      preLoaderRoute: typeof LayoutExtractRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/crawl': {
      id: '/_layout/crawl'
      path: '/crawl'
      fullPath: '/crawl'
      preLoaderRoute: typeof LayoutCrawlRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutCrawlRoute: typeof LayoutCrawlRoute
  LayoutExtractRoute: typeof LayoutExtractRoute
  LayoutGeminiResearchRoute: typeof LayoutGeminiResearchRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutMapRoute: typeof LayoutMapRoute
  LayoutPerplexityResearchRoute: typeof LayoutPerplexityResearchRoute
  LayoutSearchRoute: typeof LayoutSearchRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutCrawlRoute: LayoutCrawlRoute,
  LayoutExtractRoute: LayoutExtractRoute,
  LayoutGeminiResearchRoute: LayoutGeminiResearchRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutMapRoute: LayoutMapRoute,
  LayoutPerplexityResearchRoute: LayoutPerplexityResearchRoute,
  LayoutSearchRoute: LayoutSearchRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
